### PR TITLE
fix NumberFormatException problem

### PR DESCRIPTION
**Pull request by ILevchugov**
fix NumberFormatException problem from https://github.com/sealedtx/java-youtube-downloader/issues/110 

Used where necessary method with Long.parseLong implementation

### CODE REVIEW

**Comment by sealedtx** [comment]
@ILevchugov appreciate your work
Maybe you should also change **int** to **long** here:
https://github.com/sealedtx/java-youtube-downloader/blob/bc6d37a040cbf679ca0b68c05a532aa32ee5a18a/src/main/java/com/github/kiulian/downloader/parser/ParserImpl.java#L391-L392

And is it possible to find some testcase for request to be sure that #110 is resolved?

**Comment by ILevchugov** [comment]
@sealedtx appreciate for your feedback, I've done it.

**Comment by sealedtx** [comment]
@ILevchugov oh, my bad, I believe we can keep `videoCount` as integer to avoid further validation `videoCount < Integer.MAX_VALUE`, and most likely there won't be ever a playlist containing more than 2 billions videos, sounds unrealistic for me.
So lets revert those changes and keep `videoCount` as **integer** but `viewCount` as **long** and than I'll merge it

**Comment by sealedtx** [comment]
@ILevchugov don't forget to change `viewCount` to **long**

**Comment by ILevchugov** [comment]
@sealedtx done)

**Comment by sealedtx** [comment]
great, thank you very much

**Pull request merged**
