### PR TITLE
gets the "uploads" playlist of a channel (issue 70)

### PR DESCRIPTION
**Pull request by Fabulierer**
gets the "channel uploads" playlist by searching for a playlist on the channels main page starting with "UU" (probably stands for user uploads, only the upload playlists start with UU). Recognizes ChannelIds and custom Channel names as parameters

### CODE REVIEW

**Comment by sealedtx** [comment]
@Fabulierer Hi! Good job, thank you for your PR! I have few suggestions:
- I have found several channels where there is no "UU..." playlist on the main page of the channel. May be we should use page `https://www.youtube.com/channel/{channelId}/videos` and `https://www.youtube.com/c/{channelId}/videos`?
- Method naming could be better, mb `getChannelUploads`
- Please, stick to the existing code design (even if it is not very good), move parsing logic into the `Parser` interface and implement it in the `DefaultParser`: 
something like `public String getChannelUploadsPlaylistId(String channelId);`
- Add test

**Comment by Fabulierer** [comment]
Thanks for your feedback! I have added your suggestions and made another push.

**Comment by sealedtx** [comment]
@Fabulierer Great, thank you! One more thing, please wrap 
`BufferedReader br = new BufferedReader(new InputStreamReader(channelLink.openStream()));`
into `try catch finally` with handling `IOException` inside catch and closing `Utils.closeSilently(br)` inside finally. 
I think it would be better to keep throwing only `YoutubeException` and handle other `IOException` such as `MalformedURLException` (which won't be thrown ever, because URL is hardcoded), user should not be aware about them.

**Comment by Fabulierer** [comment]
@sealedtx All right, done! Let me know if you find anything else to change.

**Comment by sealedtx** [comment]
@Fabulierer Almost :)
```
catch (IOException ignored) {
// not simply ignore, get the message and inform user, because there could be also networks errors
// something like:
throw new YoutubeException.BadPageException(String.format("Could not load url: %s, exception: %s", url, e.getMessage());
}
finally {
    Utils.closeSilently(br);
}
throw new YoutubeException.BadPageException("Upload Playlist not found");
```

**Comment by sealedtx** [comment]
@Fabulierer Perfect, thank you very much for contributing!

**Comment by Fabulierer** [comment]
Seems like you fergot to create a release with the channel playlist feature. Could you do that now? Need it for my project ^^

**Comment by sealedtx** [comment]
@Fabulierer sure, just released 2.5.0

**Pull request merged**
