### PR TITLE
Add video.details().liveUrl()

### PR DESCRIPTION
**Pull request by poornerd**
It works for an upcoming stream, and stream that is live.

mvn -Dtest=YoutubeLiveStream_Tests test

HOWEVER, there is a period of time after a livestream is over that there are no formats available.  I will look into that, but for now this gets the live stream URL.

### CODE REVIEW

**Comment by sealedtx** [comment]
@poornerd Hi! Thanks a lot for digging into this issue, good job! Some suggestions:
1) If you accociate `liveUrl` with `VideoDetails` it would be better to keep its parsing inside `Parser#getVideoDetails` rather than in separate method `Parser#getLiveHLSUrl`? 
2) To keep tests OK you may leave these videos:
`LIVE_TEST_1` - https://www.youtube.com/watch?v=5qap5aO4i9A  - 24/7 live radio (I believe it is permament)
`WAS_LIVE_TEST_BUT_PUBLIC` - https://www.youtube.com/watch?v=boSGRDYm92E - NBC News Live - June 8 (because your video was blocked in my region)

**Comment by poornerd** [comment]
Ok @sealedtx I refactored as you suggested - It makes sense.  I added the liveURL to the constructor for VideoDetails and removed the setter.  I also updated the tests with the videos you suggested.

**Comment by sealedtx** [comment]
@poornerd Perfect, thank you

**Comment by poornerd** [comment]
@sealedtx Thanks for merging!

**Pull request merged**
